# Индексы, срезы, итерации

Одномерные массивы осуществляют операции индексирования, срезов и итераций очень схожим образом с обычными списками и другими последовательностями Python (разве что удалять с помощью срезов нельзя).

In [2]:
import numpy as np

In [4]:
a = np.arange(10) ** 3
a
a[1]
a[3:7]
a[3:7] = 8
a
a[::-1]
#del a[4:6]


for i in a:
    print(i ** (1/3))

0.0
1.0
2.0
2.0
2.0
2.0
2.0
6.999999999999999
7.999999999999999
8.999999999999998


У многомерных массивов на каждую ось приходится один индекс. Индексы передаются в виде последовательности чисел, разделенных запятыми (то бишь, кортежами):

In [5]:
b = np.array([[  0, 1, 2, 3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

b[2,3]  # Вторая строка, третий столбец
b[(2,3)]
b[2][3]  # Можно и так
b[:,2]  # Третий столбец
b[:2]  # Первые две строки
b[1:3, : : ]  # Вторая и третья строки

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

Когда индексов меньше, чем осей, отсутствующие индексы предполагаются дополненными с помощью срезов:

In [6]:
b[-1]  # Последняя строка. Эквивалентно b[-1,:]

array([40, 41, 42, 43])

b[i] можно читать как b[i, <столько символов ':', сколько нужно>]. В NumPy это также может быть записано с помощью точек, как b[i, ...].

Например, если x имеет ранг 5 (то есть у него 5 осей), тогда

x[1, 2, ...] эквивалентно x[1, 2, :, :, :],
x[... , 3] то же самое, что x[:, :, :, :, 3] и
x[4, ... , 5, :] это x[4, :, :, 5, :].

In [8]:
c = np.array([[1, 2, 3], [4, 5, 6]])
a.shape
a[1, ...]  # то же, что a[1, : , :] или a[1]
c[... ,2]  # то же, что a[: , : ,2]

array([3, 6])

Итерирование многомерных массивов начинается с первой оси:

In [15]:
for row in a:
    print(row)

0
1
8
8
8
8
8
343
512
729


Однако, если нужно перебрать поэлементно весь массив, как если бы он был одномерным, для этого можно использовать атрибут flat:

In [16]:
for el in a.flat:
    print(el)

0
1
8
8
8
8
8
343
512
729


Также можно производить математические операции между массивом и числом. В этом случае к каждому элементу прибавляется (или что вы там делаете) это число.

In [9]:
a + 1
a ** 3
a < 35  # И фильтрацию можно проводить

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False])

NumPy также предоставляет множество математических операций для обработки массивов:

In [10]:
np.cos(a)
np.arctan(a)
np.sinh(a)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:3: RuntimeWarning: overflow encountered in sinh
  app.launch_new_instance()


array([0.00000000e+000, 1.17520119e+000, 1.49047883e+003, 1.49047883e+003,
       1.49047883e+003, 1.49047883e+003, 1.49047883e+003, 4.59174009e+148,
       1.14220679e+222,             inf])

more: https://docs.scipy.org/doc/numpy/reference/routines.math.html

Многие унарные операции, такие как, например, вычисление суммы всех элементов массива, представлены также и в виде методов класса ndarray.

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(a)
a.sum()
a.min()
a.max()

6

По умолчанию, эти операции применяются к массиву, как если бы он был списком чисел, независимо от его формы. Однако, указав параметр axis, можно применить операцию для указанной оси массива:

In [12]:
a.min(axis=0)  # Наименьшее число в каждом столбце
a.min(axis=1)  # Наименьшее число в каждой строке

array([1, 4])

Одномерные массивы осуществляют операции индексирования, срезов и итераций очень схожим образом с обычными списками и другими последовательностями Python (разве что удалять с помощью срезов нельзя).

# Манипуляции с формой

Как уже говорилось, у массива есть форма (shape), определяемая числом элементов вдоль каждой оси:

In [17]:
a
a.shape

(10,)

Форма массива может быть изменена с помощью различных команд:

In [18]:
a.ravel()  # Делает массив плоским
a.shape = (6, 2)  # Изменение формы
a
a.transpose()  # Транспонирование
a.reshape((3, 4))  # Изменение формы

ValueError: cannot reshape array of size 10 into shape (6,2)

Порядок элементов в массиве в результате функции ravel() соответствует обычному "C-стилю", то есть, чем правее индекс, тем он "быстрее изменяется": за элементом a[0,0] следует a[0,1]. Если одна форма массива была изменена на другую, массив переформировывается также в "C-стиле". Функции ravel() и reshape() также могут работать (при использовании дополнительного аргумента) в FORTRAN-стиле, в котором быстрее изменяется более левый индекс.

In [19]:
a
a.reshape((3, 4), order='F')

ValueError: cannot reshape array of size 10 into shape (3,4)

Метод reshape() возвращает ее аргумент с измененной формой, в то время как метод resize() изменяет сам массив:

In [20]:
a.resize((2, 6))
a

array([[  0,   1,   8,   8,   8,   8],
       [  8, 343, 512, 729,   0,   0]])

Если при операции такой перестройки один из аргументов задается как -1, то он автоматически рассчитывается в соответствии с остальными заданными:

In [21]:
a.reshape((3, -1))

array([[  0,   1,   8,   8],
       [  8,   8,   8, 343],
       [512, 729,   0,   0]])

# Объединение массивов

Несколько массивов могут быть объединены вместе вдоль разных осей с помощью функций hstack и vstack.

hstack() объединяет массивы по первым осям, vstack() — по последним:

In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.vstack((a, b))
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Функция column_stack() объединяет одномерные массивы в качестве столбцов двумерного массива:

In [23]:
np.column_stack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Аналогично для строк имеется функция row_stack().

In [24]:
np.row_stack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Разбиение массива

Используя hsplit() вы можете разбить массив вдоль горизонтальной оси, указав либо число возвращаемых массивов одинаковой формы, либо номера столбцов, после которых массив разрезается "ножницами":

In [25]:
a = np.arange(12).reshape((2, 6))
a
np.hsplit(a, 3)  # Разбить на 3 части
np.hsplit(a, (3, 4))  # Разрезать a после третьего и четвёртого столбца

[array([[0, 1, 2],
        [6, 7, 8]]), array([[3],
        [9]]), array([[ 4,  5],
        [10, 11]])]

Функция vsplit() разбивает массив вдоль вертикальной оси, а array_split() позволяет указать оси, вдоль которых произойдет разбиение.

# Копии и представления

При работе с массивами, их данные иногда необходимо копировать в другой массив, а иногда нет. Это часто является источником путаницы. Возможно 3 случая:

# Вообще никаких копий

Простое присваивание не создает ни копии массива, ни копии его данных:

In [26]:
a = np.arange(12)
b = a  # Нового объекта создано не было
b is a  # a и b это два имени для одного и того же объекта ndarray
b.shape = (3,4)  # изменит форму a
a.shape

(3, 4)

Python передает изменяемые объекты как ссылки, поэтому вызовы функций также не создают копий.

Представление или поверхностная копия

Разные объекты массивов могут использовать одни и те же данные. Метод view() создает новый объект массива, являющийся представлением тех же данных

In [27]:
c = a.view()
c is a
c.base is a  # c это представление данных, принадлежащих a
c.flags.owndata
c.shape = (2,6)  # форма а не поменяется
a.shape
c[0,4] = 1234  # данные а изменятся
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Срез массива это представление:

In [28]:
s = a[:,1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

# Глубокая копия

Метод copy() создаст настоящую копию массива и его данных:

In [30]:
d = a.copy()  # создается новый объект массива с новыми данными
d is a
d.base is a  # d не имеет ничего общего с а
d[0, 0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])