# Random


Создавать списки, используя встроенный модуль random, а затем преобразовывать их в numpy.array:

In [1]:
import numpy as np
import random
np.array([random.random() for i in range(10)])

array([0.54357692, 0.37073335, 0.32000146, 0.81875647, 0.26052299,
       0.36743509, 0.66260158, 0.75353097, 0.97531303, 0.04846899])

Для создания массивов со случайными элементами служит модуль numpy.random.


In [2]:
import numpy as np  # Импортировать numpy и писать np.random
np.random
import numpy.random as rand  # Можно и присвоить отдельное имя. Вопрос вкуса
rand

<module 'numpy.random' from '/home/nbuser/anaconda3_501/lib/python3.6/site-packages/numpy/random/__init__.py'>

# Создание массивов

Самый простой способ задать массив со случайными элементами - использовать функцию sample (или random, или random_sample, или ranf - это всё одна и та же функция).

In [4]:
np.random.sample()


0.9626164618567533

In [5]:
np.random.sample(3)

array([0.04501765, 0.49264768, 0.13280361])

In [6]:
np.random.sample((2, 3))

array([[0.97214777, 0.27616749, 0.63926315],
       [0.9171612 , 0.61125115, 0.2535954 ]])

Без аргументов возвращает просто число в промежутке [0, 1), с одним целым числом - одномерный массив, с кортежем - массив с размерами, указанными в кортеже (все числа - из промежутка [0, 1)).

С помощью функции randint или random_integers можно создать массив из целых чисел. Аргументы: low, high, size: от какого, до какого числа (randint не включает в себя это число, а random_integers включает), и size - размеры массива.

In [7]:
np.random.randint(0, 3, 10)

array([1, 0, 0, 0, 1, 1, 2, 0, 2, 0])

In [8]:
np.random.random_integers(0, 3, 10)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 3 + 1) instead
  if __name__ == '__main__':


array([3, 1, 3, 1, 2, 2, 2, 0, 3, 3])

In [9]:
np.random.randint(0, 3, (2, 10))

array([[2, 1, 0, 2, 0, 0, 2, 1, 1, 0],
       [0, 1, 1, 2, 1, 2, 1, 0, 1, 0]])

Также можно генерировать числа согласно различным распределениям (Гаусса, Парето и другие). Чаще всего нужно равномерное распределение, которое можно получить с помощь функции uniform.

In [10]:
np.random.uniform(2, 8, (2, 10))

array([[7.61634562, 3.57246265, 4.01368064, 3.00101389, 2.89621946,
        3.05787807, 3.83253407, 7.93315806, 3.49795822, 3.09856184],
       [4.1072851 , 6.4060365 , 3.70322321, 4.13535072, 6.69256348,
        5.54819792, 6.64570984, 6.21676321, 5.22007559, 2.89813908]])

# Выбор и перемешивание

перемешать NumPy массив можно с помощью функции shuffle:

In [11]:
a = np.arange(10)
a
np.random.shuffle(a)
a

array([1, 7, 8, 6, 4, 3, 2, 0, 5, 9])

Также можно перемешать массив с помощью функции permutation (она, в отличие от shuffle, возвращает перемешанный массив). Также она, вызванная с одним аргументом (целым числом), возвращает перемешанную последовательность от 0 до N.

In [12]:
np.random.permutation(10)

array([8, 4, 1, 6, 9, 7, 5, 2, 0, 3])

Сделать случайную выборку из массива можно с помощью функции choice. Про неё стоит рассказать подробнее.

numpy.random.choice(a, size=None, replace=True, p=None)

a : одномерный массив или число. Если массив, будет производиться выборка из него. Если число, то выборка будет производиться из np.arange(a).
size : размерности массива. Если None, возвращается одно значение.
replace : если True, то одно значение может выбираться более одного раза.
p : вероятности. Это означает, что элементы можно выбирать с неравными вероятностями. Если не заданы, используется равномерное распределение.

In [13]:
a = np.arange(10)
a
np.random.choice(a, 10, p=[0.5, 0.25, 0.25, 0, 0, 0, 0, 0, 0, 0])

array([2, 0, 1, 1, 0, 2, 0, 1, 0, 0])

# Инициализация генератора случайных чисел

seed(число) - инициализация генератора.

In [17]:
np.random.seed(1000)

In [18]:
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

In [19]:
np.random.seed(1000)

In [20]:
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

get_state и set_state - возвращают и устанавливают состояние генератора.

In [21]:
np.random.seed(1000)

In [22]:
state = np.random.get_state()

In [23]:
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

In [24]:
np.random.set_state(state)

In [25]:
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])